apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  namespace: chatapp-sadiq
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: chatapp-backend
        image: sadiqaws24/chatapp-backend:v2
        ports:
        - containerPort: 5001
        env:
        - name: NODE_ENV
          value: "production"
        - name: MONGODB_URI
          value: "mongodb://mongoadmin:password@mongodb:27017/dbname?authSource=admin"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: chatapp-secret
              key: jwt_secret
        - name: PORT
          value: "5001"
        - name: FRONTEND_URL
          value: "http://localhost:3000"
